set nocompatible              " be iMproved, required
filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'tpope/vim-fugitive'
Plugin 'rust-lang/rust.vim'
Plugin 'scrooloose/syntastic'
Plugin 'kien/ctrlp.vim'
Plugin 'bling/vim-airline'
Plugin 'scrooloose/nerdtree'
Plugin 'altercation/vim-colors-solarized'
Plugin 'valloric/youcompleteme'




call vundle#end()            " required
filetype plugin indent on    " required

syntax on
filetype plugin indent on

set background=dark
let g:solarized_termcolors=256
colorscheme solarized

let g:ycm_rust_src_path="/home/pkruk/dev/rust-master/src/"

"CTRL-t to toggle tree view with CTRL-t
nmap <silent> <C-t> :NERDTreeToggle<CR>
""Set F2 to put the cursor to the nerdtree
nmap <silent> <F2> :NERDTreeFind<CR>
set mouse=a
set autoread
au CursorHold * checktime 
